"""
    LIBRARY:
    A LIBRARY IS AN ADT THAT CONTAINS:
    - ONE OR MORE COLLECTIONS
    - ONE OR MORE OBJECTS
    - LIST OF USERS WITH ACCESS
    - LIST OF IMPORTED COMMANDS COMPATIBLE WITH COLLECTIONS AND OBJECTS WITHIN THE ITSELF
    - FILE DIRECTORY
"""
