print('EXCEPTIONS TESTER')

from Handler import Handler
from Exceptions import *

handler = Handler()
handler.create_object('aiuda', {'que':'str', 'dios':'str', 'me':'str', 'acompane':'str'})
handler.create_library('test')
handler.create_collection('test', 'col', 'aiuda')
e = handler.openLibrary('nose')
print("Library nose does not exist.")
print(e.message())
handler.openLibrary('test')
e = handler.create_object('aiuda', {'que':'str', 'hostia':'str'})
print("\nAn object with the name aiuda already exists.")
print(e.message())
e = handler.openLibrary('test')
print("\nLibrary test is already opened.")
print(e.message())
e = handler.close_library('mierda')
print("\nLibrary mierda is not opened.")
print(e.message())
e = handler.create_library('test')
print("\nA library with the name test already exists.")
print(e.message())
e = handler.create_collection('test', 'yizus', 'none')
print("\nObject none does not exist.")
print(e.message())
e = handler.create_collection('test', 'col', 'aiuda')
print("\nA collection with the name col already exists.")
print(e.message())
e = handler.remove_collection_from_library('test', 'help')
print("\nCollection help does not exist.")
print(e.message())
e = handler.remove_object_from_collection('test', 'col', 2)
print("\nAn object with index 2 does not exist.")
print(e.message())
e = handler.sort('test', 'col', 'medalla')
print("\nAttribute medalla does not exist.")
print(e.message())
